version: 0.0
os: linux
files:
  - source: build/libs/fluffytime-0.0.1-SNAPSHOT.jar
    destination: /home/fluffytime/server

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: fluffytime_user

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: fluffytime_user

  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: fluffytime_user
